# version: '3.6'

services: 
    db:
        container_name: mysql-docker
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        # Opsional. Hilangkan komen dibawah ini jika komputer Anda tidak menggunakan prosesor arsitektur x86_64 atau komputer Anda menggunakan Apple Silicon / arm64.
        # platform: linux/amd64
        restart: always
        volumes: 
            - ./mysql-data:/var/lib/mysql
        ports: 
            - 8001:3306
        environment:
            MYSQL_DATABASE: 'akademik'
            MYSQL_USER: 'db-operator'
            MYSQL_PASSWORD: 'dockerized1970'
            MYSQL_ROOT_PASSWORD: 'database-master'
