/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tupayproject;

import javax.swing.*;
import java.sql.*;

/**
 * @author zen
 */
public class Form_SPP_Mahasiswa extends javax.swing.JFrame {
	/**
	 * Creates new form Form_SPP_Mahasiswa
	 */
	public Form_SPP_Mahasiswa() {
		initComponents();
		setLocationRelativeTo(null);
		setResizable(false);

		//Membuat text area tidak bisa diedit
		ta_print.setEditable(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// Menampilkan hasil data masukan SPP mahasiswa sebelum disimpan ke database.
	public void printAll() {
		// Membuat StringBuilder untuk mengabunggkan teks.
		StringBuilder sb = new StringBuilder();

		// Menggabungkan String yang ada pada setiap kolom menjadi satu.
		sb.append("\n\n------- Student Tuition Bill Info -------\n");
		sb.append("\nStudent Name\t\t : " + txt_name.getText());
		sb.append("\nStudent ID\t\t : " + txt_StudentNumber.getText());
		sb.append("\nStudent Batch\t\t : " + cmb_generation.getSelectedItem());
		sb.append("\nSemester\t\t : " + cmb_semester.getSelectedItem());
		sb.append("\nFaculty\t\t : " + cmb_faculty.getSelectedItem());
		sb.append("\nMajor Study\t\t : " + cmb_departement.getSelectedItem());
		sb.append("\nCredit total\t\t : " + txt_credits.getText());
		sb.append("\n\n");
		sb.append("\nFixed Tuition Bill\t : " + TuitionBill.TB_Fixed(cmb_generation.getSelectedIndex(), cmb_faculty.getSelectedIndex()));
		sb.append("\nVariable Tuition Bill\t : " + TuitionBill.TB_Variable(cmb_generation.getSelectedIndex(), cmb_departement.getSelectedIndex(), Double.parseDouble(txt_credits.getText())));
		sb.append("\nTuition Bill Total\t : " + TuitionBill.TB_Total(cmb_generation.getSelectedIndex(), cmb_faculty.getSelectedIndex(), cmb_departement.getSelectedIndex(), Double.parseDouble(txt_credits.getText())) + "\n\n\n\n");
		ta_print.setText(sb.toString());
	}

	// Menghapus seluruh inputan user.
	public void hapus() {
		txt_StudentNumber.setText(null);
		txt_credits.setText(null);
		txt_name.setText(null);
		cmb_departement.setSelectedIndex(0);
		cmb_faculty.setSelectedIndex(0);
		cmb_generation.setSelectedIndex(0);
		cmb_semester.setSelectedIndex(0);
		ta_print.setText(null);
	}

	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		txt_StudentNumber = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		txt_name = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		cmb_faculty = new javax.swing.JComboBox<>();
		jLabel7 = new javax.swing.JLabel();
		cmb_departement = new javax.swing.JComboBox<>();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		cmb_semester = new javax.swing.JComboBox<>();
		cmb_generation = new javax.swing.JComboBox<>();
		jLabel10 = new javax.swing.JLabel();
		txt_credits = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		btn_check = new javax.swing.JButton();
		jLabel12 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		ta_print = new javax.swing.JTextArea();
		btn_reset = new javax.swing.JButton();
		btn_submit = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
		jLabel1.setText("TUITION PAYMENT FORM");

		jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
		jLabel2.setText("UNIVERSITAS TEKNOLOGI YOGYAKARTA");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGap(360, 360, 360)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
										.addComponent(jLabel2)
										.addComponent(jLabel1))
								.addGap(360, 360, 360))
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jSeparator1))
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGap(18, 18, 18)
								.addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel2)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap())
		);

		jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
		jLabel3.setText("Transaction Form");

		jLabel4.setText("Student number");

		txt_StudentNumber.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txt_StudentNumberActionPerformed(evt);
			}
		});

		jLabel5.setText("Name");

		jLabel6.setText("Faculty");

		cmb_faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Faculty of Business and Humanities", "Faculty of Science and Technology", "Diploma Program"}));

		jLabel7.setText("Major");

		cmb_departement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Informatics", "Electrical Engineering", "Management", "Accounting", "Tourism", "Computer Engineering"}));

		jLabel8.setText("Student batch");

		jLabel9.setText("Current semester");

		cmb_semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1", "2", "3", "4", "5", "6", "7", "8"}));

		cmb_generation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"2021", "2020", "2019", "2018", "2017", "2016"}));

		jLabel10.setText("Course credits");

		jLabel11.setText("Credits");

		btn_check.setText("Check");
		btn_check.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_checkMouseClicked(evt);
			}
		});
		btn_check.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_checkActionPerformed(evt);
			}
		});

		jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
		jLabel12.setText("Transaction Data");

		ta_print.setColumns(20);
		ta_print.setRows(5);
		jScrollPane1.setViewportView(ta_print);

		btn_reset.setBackground(new java.awt.Color(127, 35, 35));
		btn_reset.setForeground(new java.awt.Color(255, 255, 255));
		btn_reset.setText("Reset");
		btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_resetMouseClicked(evt);
			}
		});

		btn_submit.setBackground(new java.awt.Color(58, 120, 58));
		btn_submit.setForeground(new java.awt.Color(255, 255, 255));
		btn_submit.setText("Submit");
		btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_submitMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap())
						.addGroup(layout.createSequentialGroup()
								.addGap(108, 108, 108)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel3)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel4)
														.addComponent(jLabel5)
														.addComponent(jLabel6)
														.addComponent(jLabel7)
														.addComponent(jLabel8)
														.addComponent(jLabel9)
														.addComponent(jLabel10))
												.addGap(65, 65, 65)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
														.addComponent(txt_StudentNumber)
														.addComponent(txt_name)
														.addComponent(cmb_faculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(cmb_departement, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																.addComponent(cmb_semester, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(cmb_generation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup()
																.addComponent(txt_credits, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18)
																.addComponent(jLabel11))))
										.addComponent(btn_check, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel12)
														.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(62, 62, 62))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
												.addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(27, 27, 27)
												.addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(83, 83, 83))))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3)
										.addComponent(jLabel12))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(txt_StudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(20, 20, 20)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(cmb_faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(cmb_departement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(cmb_generation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel9)
														.addComponent(cmb_semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel10)
														.addComponent(txt_credits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel11)))
										.addComponent(jScrollPane1))
								.addGap(29, 29, 29)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btn_check, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(29, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkActionPerformed
		// ABAIKAN
	}//GEN-LAST:event_btn_checkActionPerformed

	private void txt_StudentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_StudentNumberActionPerformed
		// ABAIKAN
	}//GEN-LAST:event_txt_StudentNumberActionPerformed

	private void btn_checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_checkMouseClicked
		this.printAll();
	}//GEN-LAST:event_btn_checkMouseClicked

	private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
		this.hapus();
	}//GEN-LAST:event_btn_resetMouseClicked

	private void btn_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseClicked
		try {
			Connection connection = DBConnection.connectDB("8001"); // Anda dapat menggantinya menjadi 3306 (Port default) jika Anda tidak ingin menggunakan Docker sebagai tempat database.

			// Menyiapkan query MySQL sebelum di eksekusi.
			PreparedStatement queryStatement = connection.prepareStatement("insert into transaction_list (student_name, student_id, student_faculty, student_major, student_batch, student_semester, student_credit, cf_fixed, cf_variable, cf_total) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

			// Memasukkan variabel-variabel yang ada pada setiap kolom formulir kedalam query MySQL.
			queryStatement.setString(1, txt_name.getText());
			queryStatement.setString(2, txt_StudentNumber.getText());
			queryStatement.setString(3, cmb_faculty.getSelectedItem().toString());
			queryStatement.setString(4, cmb_departement.getSelectedItem().toString());
			queryStatement.setString(5, cmb_generation.getSelectedItem().toString());
			queryStatement.setString(6, cmb_semester.getSelectedItem().toString());
			queryStatement.setInt(7, Integer.parseInt(txt_credits.getText()));

			queryStatement.setDouble(8, TuitionBill.TB_Fixed(cmb_generation.getSelectedIndex(), cmb_faculty.getSelectedIndex()));
			queryStatement.setDouble(9, TuitionBill.TB_Variable(cmb_generation.getSelectedIndex(), cmb_departement.getSelectedIndex(), Double.parseDouble(txt_credits.getText())));
			queryStatement.setDouble(10, TuitionBill.TB_Total(cmb_generation.getSelectedIndex(), cmb_faculty.getSelectedIndex(), cmb_departement.getSelectedIndex(), Double.parseDouble(txt_credits.getText())));

			queryStatement.execute(); // Jalankan query yang telah disiapkan.

			JOptionPane.showMessageDialog(this, "Data has been successfully saved.", "Success", JOptionPane.INFORMATION_MESSAGE);
			dispose();
			new History_Transaction(txt_name.getText()).setVisible(true);
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(this, "Failed to save a data. Please try again.", "Error occured.", JOptionPane.ERROR_MESSAGE);

			// Kembali ke halaman awal jika terjadi kesalahan
			dispose();
			new Home().setVisible(true);
			e.printStackTrace();
		}
	}//GEN-LAST:event_btn_submitMouseClicked

	/**
	 * @param args the command line arguments
	 */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_SPP_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_SPP_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_SPP_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_SPP_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_SPP_Mahasiswa().setVisible(true);
//            }
//        });
//    }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btn_check;
	private javax.swing.JButton btn_reset;
	private javax.swing.JButton btn_submit;
	private javax.swing.JComboBox<String> cmb_departement;
	private javax.swing.JComboBox<String> cmb_faculty;
	private javax.swing.JComboBox<String> cmb_generation;
	private javax.swing.JComboBox<String> cmb_semester;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextArea ta_print;
	private javax.swing.JTextField txt_StudentNumber;
	private javax.swing.JTextField txt_credits;
	private javax.swing.JTextField txt_name;
	// End of variables declaration//GEN-END:variables
}
