/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tupayproject;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.WindowListener;
import java.sql.*;

/**
 * @author zen
 */
public class Home extends javax.swing.JFrame {

	/**
	 * Creates new form Home
	 */
	public Home() {
		initComponents();
		setLocationRelativeTo(null);
		setResizable(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		btn_masuk_mahasiswa = new javax.swing.JButton();
		btn_masuk_admin = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
		jLabel1.setText("TUPAY");

		jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
		jLabel2.setText("Universitas Teknologi Yogyakarta");

		jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
		jLabel3.setText("TUPAY make tuition payment easier, faster,");

		jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
		jLabel4.setText("and more eficient.");

		btn_masuk_mahasiswa.setBackground(new java.awt.Color(0, 0, 0));
		btn_masuk_mahasiswa.setForeground(new java.awt.Color(255, 255, 255));
		btn_masuk_mahasiswa.setText("College Student");
		btn_masuk_mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_masuk_mahasiswaMouseClicked(evt);
			}
		});
		btn_masuk_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_masuk_mahasiswaActionPerformed(evt);
			}
		});

		btn_masuk_admin.setBackground(new java.awt.Color(0, 0, 0));
		btn_masuk_admin.setForeground(new java.awt.Color(255, 255, 255));
		btn_masuk_admin.setText("Admin");
		btn_masuk_admin.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_masuk_adminMouseClicked(evt);
			}
		});

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tupayproject/group-1.png"))); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGap(73, 73, 73)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel1)
										.addComponent(jLabel2)
										.addComponent(jLabel3)
										.addComponent(jLabel4)
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(btn_masuk_mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(btn_masuk_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
								.addComponent(jLabel5)
								.addGap(69, 69, 69))
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGap(82, 82, 82)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel5)
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(jLabel1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel2)
												.addGap(18, 18, 18)
												.addComponent(jLabel3)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel4)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(btn_masuk_mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(btn_masuk_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addContainerGap(112, Short.MAX_VALUE))
		);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap())
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btn_masuk_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masuk_mahasiswaActionPerformed
		// ABAIKAN
	}//GEN-LAST:event_btn_masuk_mahasiswaActionPerformed

	private void btn_masuk_mahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masuk_mahasiswaMouseClicked
		dispose();
		new Form_SPP_Mahasiswa().setVisible(true);
	}//GEN-LAST:event_btn_masuk_mahasiswaMouseClicked

	private void btn_masuk_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masuk_adminMouseClicked

		// Header dialog
		JLabel headerDialog = new JLabel("Enter an administrator username and password.", JLabel.CENTER);
		headerDialog.setFont(new Font(Font.DIALOG, Font.BOLD, 18));
		headerDialog.setBorder(new EmptyBorder(12, 0, 12, 0));

		// Komponen untuk membuat dialog username dan password.
		JTextField usernameInput = new JTextField();
		JPasswordField passwordInput = new JPasswordField();

		usernameInput.setColumns(24);
		passwordInput.setColumns(24);

		final JComponent[] inputs = new JComponent[]{
				headerDialog,
				new JLabel("Username"), usernameInput,
				new JLabel("Password"), passwordInput
		};

		// Menampilkan dialog autentikasi.
		int result = JOptionPane.showConfirmDialog(this, inputs, "Authentication required", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
		if (result == JOptionPane.OK_OPTION) {
			try {
				Connection connection = DBConnection.connectDB("3306"); // Anda dapat menggantinya menjadi 3306 (Port default) jika Anda tidak ingin menggunakan Docker sebagai tempat database.

				Statement validationStatement = connection.createStatement();
				try {
					ResultSet data = validationStatement.executeQuery("select * from administrator");

					// Mengelilingi hasil data kueri untuk memeriksa apa data yang dimasukkan pengguna ada dalam database.
					while (data.next()) {
						String stringPass = new String(passwordInput.getPassword()); // Mengubah tipe char dari JPasswordField menjadi String.

						// Jika username dan password benar maka halaman Admin_TransactionList() akan muncul. Jika tidak maka akan ditampilkan sebuah pesan kesalahan.
						// Pada kondisi ini juga terdapat kelas DataHash yang berfungsi untuk mengubah String pada variabel stringPass menjadi SHA-256 dengan alasan untuk keamanan akun admin.
						if (usernameInput.getText().equals(data.getString(2)) && DataHash.SHA256Text(stringPass).equals(data.getString(3))) {
							dispose();
							new Admin_TransactionList().setVisible(true);
							break;
						} else {
							JOptionPane.showMessageDialog(null, "Username or password is incorrect.", "Error", JOptionPane.ERROR_MESSAGE);
							break;
						}
					}
				} catch (SQLException e) {
					JOptionPane.showMessageDialog(null, "Something is wrong, please try again.", "Error", JOptionPane.ERROR_MESSAGE);
					e.printStackTrace();
				}
			} catch (SQLException e) {
				// Kesalahan yang akan muncul jika koneksi pada database tidak berhasil.
				JOptionPane.showMessageDialog(null, "Error occured getting connection to database. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
				e.printStackTrace();
			}
		}
	}//GEN-LAST:event_btn_masuk_adminMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String[] args) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Home().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btn_masuk_admin;
	private javax.swing.JButton btn_masuk_mahasiswa;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables
}
